
set t_Co=256

filetype on
syntax on


" Needed for Powerline
set nocompatible
set laststatus=2
set encoding=utf-8

autocmd BufWritePre *.py :%s/\s\+$//e

:nnoremap <silent> <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>

" Toggle line numbers
:nmap \l :setlocal number!<CR>

" Toggle paste mode
:nmap \o :set paste!<CR>

" Move by screen lines, not file lines
:nmap j gj
:nmap k gk

" Search settings
:set incsearch
":set ignorecase
:set smartcase
:set hlsearch
:nmap \q :nohlsearch<CR>

" tab junk
:nmap \t :set expandtab tabstop=4 shiftwidth=4 softtabstop=4<CR>
:nmap \T :set expandtab tabstop=8 shiftwidth=8 softtabstop=4<CR>
:nmap \M :set noexpandtab tabstop=8 shiftwidth=4 softtabstop=4<CR>
:nmap \m :set expandtab tabstop=2 shiftwidth=2 softtabstop=2<CR>
:set expandtab tabstop=4 shiftwidth=4 softtabstop=4

" Force Tabs for Makefiles
:autocmd FileType make set noexpandtab

" Toggle line wrap
:nmap \w :setlocal wrap!<CR>:setlocal wrap?<CR>

